### PR TITLE
Update install_mobile_setup.md

### PR DESCRIPTION
**Pull request by AmiableAnil**
I have added step to set up sunbird mobile.

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @AmiableAnil,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/153.

**Comment by lakhanmandloi** [comment]
Hello @AmiableAnil,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/153.

**Comment by lakhanmandloi** [comment]
Hello @AmiableAnil,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/153.

**Comment by nawabahmadreshi** [comment]
@AmiableAnil 
Clone GitHub `sunbird-android` repo into it.

what is the path of the Sunbird android git codebase ?

**Comment by lakhanmandloi** [comment]
Hello @AmiableAnil,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/153.

**Comment by lakhanmandloi** [comment]
Hello @AmiableAnil,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/153.

**Comment by lakhanmandloi** [comment]
Hello @AmiableAnil,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/153.

**Comment by lakhanmandloi** [comment]
Hello @AmiableAnil,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/153.

**Comment by lakhanmandloi** [comment]
Hello @AmiableAnil,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/153.

**Comment by lakhanmandloi** [comment]
Hello @AmiableAnil,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/153.

**Comment by lakhanmandloi** [comment]
Hello @AmiableAnil,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/153.

**Comment by lakhanmandloi** [comment]
Hello @AmiableAnil,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/153.

**Comment by lakhanmandloi** [comment]
Hello @AmiableAnil,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/153.

**Pull request merged**
