### PR TITLE
channel filtering page

### PR DESCRIPTION
**Pull request by deepshikha2k5**
- [ ] Have you followed [Contribution Guidelines](http://www.sunbird.org/contributions/contribution_guidelines/)
sending you the channel filtering page to be merged 
-----

### CODE REVIEW

**Comment by deepshikha2k5** [comment]
Please review the channel filtering page

**Comment by lakhanmandloi** [comment]
Hello @deepshikha2k5,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/478. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/478/developer-docs/configuring_sunbird/channel_based_filtering <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @deepshikha2k5,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/478. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/478/developer-docs/configuring_sunbird/channel_based_filtering <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @deepshikha2k5,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/478. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/478/developer-docs/configuring_sunbird/channel_based_filtering <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @deepshikha2k5,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/478. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/478/developer-docs/configuring_sunbird/channel_based_filtering <br />  <br/> **Modified sections are -** <br />

**Pull request merged**
