### PR TITLE
Update channel_reg_with_ekstep.md

### PR DESCRIPTION
**Pull request by nawabahmadreshi**
Update the "register a channel with Ekstep" content

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @nawabahmadreshi,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/309.

**Comment by nawabahmadreshi** [comment]
Sent for internal review

**Comment by lakhanmandloi** [comment]
Hello @nawabahmadreshi,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/309.

**Comment by lakhanmandloi** [comment]
Hello @nawabahmadreshi,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/309.

**Comment by lakhanmandloi** [comment]
Hello @nawabahmadreshi,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/309.

**Comment by lakhanmandloi** [comment]
Hello @nawabahmadreshi,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/309. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/309/developer-docs/channel_reg_with_ekstep <br />  <br/> **Modified sections are -** <br />

**Pull request merged**
