### PR TITLE
Issue #8 feat: Deploy to prod - Tag dev.2.0.10

### PR DESCRIPTION
**Pull request by lakhanmandloi**

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
@kochhar @coolbung @parthlawate @nawabahmadreshi - Can you pls accept this PR ?
Site can be reviewed at - http://sunbird-trial.s3-website.ap-south-1.amazonaws.com/
cc: 
@Sunitashelar @deepshikha2k5

**Comment by nawabahmadreshi** [comment]
Done , Merged the PR .
@lakhanmandloi 

cc:
@Sunitashelar

**Comment by lakhanmandloi** [comment]
@nawabahmadreshi Thank you so much Nawab . Changes are reflecting without any hard refresh. :)
Thank you so much @nawabahmadreshi @deepshikha2k5 @Sunitashelar :)

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi 
Your support and coordination is appreciated. Thanks a lot for being so helpful.

**Pull request merged**
