### PR TITLE
adding spaces between list

### PR DESCRIPTION
**Pull request by nawabahmadreshi**

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @nawabahmadreshi,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/304.

**Comment by lakhanmandloi** [comment]
Hello @nawabahmadreshi,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/304.

**Comment by lakhanmandloi** [comment]
Hello @nawabahmadreshi,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/304.

**Comment by Sunitashelar** [comment]
Closing the PR without merging it as new PR will be generated for the changes requested.

**Pull request closed without merging**
