### PR TITLE
Requesting you to merge this PR 

### PR DESCRIPTION
**Pull request by deepshikha2k5**
- [ ] Have you followed [Contribution Guidelines](http://www.sunbird.org/contributions/contribution_guidelines/)

-----

### CODE REVIEW

**Comment by deepshikha2k5** [comment]
@Sunitashelar 

Please merge this PR in order to edit the files that I have committed. Thanks

**Comment by lakhanmandloi** [comment]
Hello @deepshikha2k5,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/504. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/504/features-documentation/course_workflow/abc <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/504/features-documentation/course_workflow/adding_metadata <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/504/features-documentation/course_workflow/course_creation_overview <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/504/features-documentation/course_workflow/exploring_toc <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/504/features-documentation/course_workflow/prerequisite <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/504/features-documentation/course_workflow/start_creating <br />  <br/> **Modified sections are -** <br />

**Comment by Sunitashelar** [comment]
Closing this PR without merging it as there is an issue

**Comment by lakhanmandloi** [comment]
@deepshikha2k5 It would be better to delete pages which do not have any content and front matter. 
404 pages are result of empty md files. 

@Sunitashelar

**Pull request closed without merging**
