### PR TITLE
Correction technical errors

### PR DESCRIPTION
**Pull request by rjshrjndrn**

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/186.

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/186.

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/186.

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/186.

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/186.

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/186.

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/186.

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/186.

**Comment by deepshikha2k5** [comment]
The typo and grammatical error is fixed

**Pull request merged**
