### PR TITLE
Portal setup instructions update as per release-1.3

### PR DESCRIPTION
**Pull request by harishgilimi**

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @harishgilimi,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/146.

**Comment by harishgilimi** [comment]
Hi @lakhanmandloi ,
Looks good in http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/146.
@kochhar @nawabahmadreshi  please review and merge

**Comment by nawabahmadreshi** [comment]
@kochhar , can you please verify the contents so that I proceed with updations. 
cc:
@Sunitashelar

**Comment by kochhar** [comment]
@nawabahmadreshi formatting looks good -- one error in this line
> For setting up the application,check out the code here.

There should be a space after the comma. Please fix and merge.

**Comment by nawabahmadreshi** [comment]
@kochhar 
can you please verify the content ?

**Comment by kochhar** [comment]
Version on /pr/146 has some errors.

**Comment by nawabahmadreshi** [comment]
@kochhar 
Errors in what context ?

**Comment by kochhar** [comment]
Formatting and layout errors.

**Comment by nawabahmadreshi** [comment]
done

**Pull request merged**
