### PR TITLE
DIAL API's updated

### PR DESCRIPTION
**Pull request by harishgilimi**

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @harishgilimi,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/356. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/356/apis/dialapi/ <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @harishgilimi,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/356. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/356/apis/dialapi/ <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @harishgilimi,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/356. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/356/apis/dialapi/ <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @harishgilimi,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/356. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/356/apis/dataexhaustapi/ <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/356/apis/dialapi/ <br />  <br/> **Modified sections are -** <br />

**Comment by Sunitashelar** [comment]
@harishgilimi The descriptions for DIAL APIs have been deleted in most places. Could you please check and update. I am closing this PR. Send a new PR for the DIAL APIs as the Data Exhaust APIs have been published separately.

**Pull request closed without merging**
