### PR TITLE
Issue #6 feat: Add FAQ Section and Update API's

### PR DESCRIPTION
**Pull request by lakhanmandloi**

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
@nawabahmadreshi @Sunitashelar @deepshikha2k5 - Pls confirm This build is good to go on Live - http://sunbird-trial.s3-website.ap-south-1.amazonaws.com/ . Pls verify FAQs, API's Section and other. Do hard refresh. 

@coolbung Can you pls accept the MR post apporval ?

Thanks!

cc: 
@parthlawate @kochhar

**Comment by nawabahmadreshi** [comment]
@lakhanmandloi  , The website seems pretty ok to go live for now .
Also ,as already discussed.  A few more tweaks need to be done (regarding Sidebar) , we can do that on Monday .

cc:
@Sunitashelar

**Comment by parthlawate** [comment]
@lakhanmandloi appreciate the quick inputs on this inspite of the Societal deadlines 👍  Good job ! @coolbung is down with fever can I help in anyway for any MR Acceptance ?

**Comment by lakhanmandloi** [comment]
@nawabahmadreshi @parthlawate Thank you :)

**Pull request merged**
