### PR TITLE
Update howto_create_org_add_user.md

### PR DESCRIPTION
**Pull request by manzarul**
Issues #SB-3231  fix: adding documentation which will explain how to create user , org and then user-org association.

- [ ] Have you followed [Contribution Guidelines](http://www.sunbird.org/contributions/contribution_guidelines/)

-----

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @manzarul,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/404. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/404/howto/howto_create_org_add_user <br />  <br/> **Modified sections are -** <br />

**Comment by deepshikha2k5** [comment]
This information will be added in the How-to-section by the end of Release 1.7.0

**Comment by manzarul** [comment]
Hi  Why this pull request is not reviewed and merge yet.

**Comment by Sunitashelar** [comment]
Closing this PR without merging it as the content has been incorporated into another page.

**Pull request closed without merging**
