### PR TITLE
Issues #SB-00 fix: adding all possible env variable which sunbird lms…

### PR DESCRIPTION
**Pull request by manzarul**
… service is using

- [ ] Have you followed [Contribution Guidelines](http://www.sunbird.org/contributions/contribution_guidelines/)

-----

### CODE REVIEW

**Comment by nawabahmadreshi** [comment]
@manzarul  Kindly let us know where this should be placed in sidebar ?

**Comment by manzarul** [comment]
HI Nawab,
                 Really i don't know, but assuming some where after sunbird
installation or one of installation check list. Please check with Shailesh.

*Md Manzarul haque*

*Phone NO: 9663890445*

**Comment by mathewjpallan** [comment]
This has to be a sub-section "Configuring Sunbird" within the Installation section. Rather than having all the variables listed here, we should only have the variables that are actually required in configuring sunbird behavior. For eg. we should not document variables like sunbird_cassandra_host which do not help with sunbird behavior and are taken care of by the installation as such. However we would want to allow configuring email parameters to allow Sunbird to send out emails and these parameters should be documented.

@deepshikha2k5 @manzarul @vrayulu

**Comment by Sunitashelar** [comment]
Closing this PR as a new page has been created as per comments given by Mathew. The page has been circulated for information on May 23, 2018. Link to page is:
http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/review/developer-docs/configuring_sunbird/

**Pull request closed without merging**
