### PR TITLE
SB-8827: Reserve and Release Dialcode API Document

### PR DESCRIPTION
**Pull request by amitpriyadarshi**
- [ ] Have you followed [Contribution Guidelines](http://www.sunbird.org/contributions/contribution_guidelines/)

-----

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @amitpriyadarshi,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/677. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/677/apis/dialapi/ <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
@amitpriyadarshi this is wrong repo. Correct repo is -https://github.com/project-sunbird/sunbird.org-docs/

cc: @Sunitashelar @Basreena

**Comment by lakhanmandloi** [comment]
Hello @amitpriyadarshi,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/677. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/677/apis/dialapi/ <br />  <br/> **Modified sections are -** <br />

**Comment by Sunitashelar** [comment]
Merging the PR. But, there are places where values are empty. This needs to be corrected across API reference docs.

**Pull request merged**
