### PR TITLE
Update and rename env_variables.md to env_variables_lms.md

### PR DESCRIPTION
**Pull request by nawabahmadreshi**
- [ ] Have you followed [Contribution Guidelines](http://www.sunbird.org/contributions/contribution_guidelines/)

-----

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @nawabahmadreshi,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/469. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/469/developer-docs/configuring_sunbird/env_variables_lms <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @nawabahmadreshi,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/469. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/469/developer-docs/configuring_sunbird/env_variables <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/469/developer-docs/configuring_sunbird/env_variables_lms <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @nawabahmadreshi,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/469. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/469/developer-docs/configuring_sunbird/env_variables <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/469/developer-docs/configuring_sunbird/env_variables_lms <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @nawabahmadreshi,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/469. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/469/developer-docs/configuring_sunbird/env_variables <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/469/developer-docs/configuring_sunbird/env_variables_lms <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @nawabahmadreshi,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/469. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/469/developer-docs/configuring_sunbird/env_variables <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/469/developer-docs/configuring_sunbird/env_variables_lms <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @nawabahmadreshi,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/469. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/469/developer-docs/configuring_sunbird/env_variables <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/469/developer-docs/configuring_sunbird/env_variables_lms <br />  <br/> **Modified sections are -** <br />

**Comment by Sunitashelar** [comment]
Closing this PR without merging it as there is another PR for the same.

**Pull request closed without merging**
