### PR TITLE
Please change the name CONTENT EDITOR to Study material

### PR DESCRIPTION
**Pull request by vinukumar-vs**
Please change the name CONTENT EDITOR to STUDY MATERIAL

We have links to Courses, Collection, Book, Lesson Plan etc.. But we are calling Study Material as Content Editor which is technical term user don't know what is it mean

- [ ] Have you followed [Contribution Guidelines](http://www.sunbird.org/contributions/contribution_guidelines/)

-----

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @vinukumar-vs,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/380. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/380/features-documentation/contenteditor <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @vinukumar-vs,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/380. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/380/features-documentation/contenteditor <br />  <br/> **Modified sections are -** <br />

**Comment by Sunitashelar** [comment]
Not changing the name of this file. But taking your point and will add a page on Study Material. This is because the content of the page describes how to use the content editor with all its features.

**Comment by lakhanmandloi** [comment]
Hello @vinukumar-vs,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/380. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/380/features-documentation/contenteditor <br />  <br/> **Modified sections are -** <br />

**Pull request merged**
