### PR TITLE
upload existing content

### PR DESCRIPTION
**Pull request by seventunes**
- [ ] Have you followed [Contribution Guidelines](http://www.sunbird.org/contributions/contribution_guidelines/)

-----

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @seventunes,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/developer-docs/how-to-guide/How_to_ upload_existing_content_using _sunbird (1) <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/developer-docs/installation/install_mobile_setup <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/features-documentation/collection_creation <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/features-documentation/course_creation <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/features-documentation/lessonplan <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/howto/upload_existing_content <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @seventunes,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/developer-docs/how-to-guide/How_to_ upload_content_on_Sunbird <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/developer-docs/installation/install_mobile_setup <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/features-documentation/collection_creation <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/features-documentation/course_creation <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/features-documentation/lessonplan <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/howto/upload_existing_content <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @seventunes,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/developer-docs/how-to-guide/How_to_ upload_content_on_Sunbird <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/developer-docs/installation/install_mobile_setup <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/features-documentation/collection_creation <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/features-documentation/course_creation <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/features-documentation/lessonplan <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/howto/upload_existing_content <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @seventunes,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/developer-docs/how-to-guide/How_to_ upload_existing_content_using _sunbird (1) <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/developer-docs/installation/install_mobile_setup <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/features-documentation/collection_creation <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/features-documentation/course_creation <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/features-documentation/lessonplan <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/658/howto/upload_existing_content <br />  <br/> **Modified sections are -** <br />

**Comment by Sunitashelar** [comment]
Closing this PR without merging it as there are some conflicts in the commits. Would like to check your branch, and send new PRs before any merges are made.

**Pull request closed without merging**
