### PR TITLE
Sunbird user profile extension

### PR DESCRIPTION
**Pull request by bvinayakumar**
- [ ] Have you followed [Contribution Guidelines](http://www.sunbird.org/contributions/contribution_guidelines/)

-----

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @bvinayakumar,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/564. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/564/developer-docs/opensaber/user_extension <br />  <br/> **Modified sections are -** <br />

**Comment by manzarul** [comment]
Ticket Ref:  SB-4403

**Comment by lakhanmandloi** [comment]
Hello @bvinayakumar,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/564. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/564/developer-docs/opensaber/user_extension <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @bvinayakumar,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/564. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/564/developer-docs/opensaber/user_extension <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @bvinayakumar,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/564. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/564/developer-docs/opensaber/user_extension <br />  <br/> **Modified sections are -** <br />

**Pull request merged**
