### PR TITLE
Updated Upgrade doc

### PR DESCRIPTION
**Pull request by rjshrjndrn**
- [x] Have you followed [Contribution Guidelines](http://www.sunbird.org/contributions/contribution_guidelines/)

-----

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/653. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/653/developer-docs/upgrading <br />  <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/653. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/653/developer-docs/upgrading <br />  <br/> **Modified sections are -** <br />

**Comment by rjshrjndrn** [comment]
@Sunitashelar  Removed prerequisites, and pulling the latest code in line num: 114

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/653. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/653/developer-docs/upgrading <br />  <br/> **Modified sections are -** <br />

**Pull request merged**
