### PR TITLE
Organisation changes sb 2922

### PR DESCRIPTION
**Pull request by manzarul**
- [x] Have you followed [Contribution Guidelines](http://www.sunbird.org/contributions/contribution_guidelines/)
 fixes for Jira issues SB-2922 and SB-2652
-----

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @manzarul,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/390. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/390/apis/locationMasterDataService/ <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/390/apis/locationMasterDataService/ <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/390/apis/locationMasterDataService/ <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/390/apis/locationMasterDataService/ <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/390/apis/orgapi/ <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/390/apis/pagesapi/ <br />  <br/> **Modified sections are -** <br />

**Comment by manzarul** [comment]
Fixes for Page api  and add user to org.

**Comment by lakhanmandloi** [comment]
Hello @manzarul,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/390. <br/><br/> **Modified pages are -** <br />- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/390/apis/locationMasterDataService/ <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/390/apis/locationMasterDataService/ <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/390/apis/locationMasterDataService/ <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/390/apis/locationMasterDataService/ <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/390/apis/orgapi/ <br /> - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/390/apis/pagesapi/ <br />  <br/> **Modified sections are -** <br />

**Comment by manzarul** [comment]
verify and update the pull request . changes is in page api url and some of the request body. and add user to org api inside organisation api.

**Comment by Sunitashelar** [comment]
@manzarul Please raise a separate PR only for the updated API files - org.api & pages.api. 
the other 4 files will not be merged until we have clarity on whether we should include DIKSHA specific service APIs in this repo.

**Comment by manzarul** [comment]
@nawabahmadreshi  , i create a new pull request with only those two files change .
Ref : https://github.com/project-sunbird/project-sunbird.github.io/pull/391/
You can delete this one.
cc: @Sunitashelar

**Pull request closed without merging**
