### PR TITLE
added steps to onboard announcements

### PR DESCRIPTION
**Pull request by gsbajaj72**

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @gsbajaj72,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/218.

**Comment by lakhanmandloi** [comment]
Hello @gsbajaj72,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/218.

**Comment by lakhanmandloi** [comment]
Hello @gsbajaj72,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/218.

**Comment by deepshikha2k5** [comment]
Content edited and merged. All the required changes and links added to the document.

**Pull request merged**
