### PR TITLE
Sunbird simplified installation

### PR DESCRIPTION
**Pull request by rjshrjndrn**
Documentation for new installation method for sunbird medium scale.

### CODE REVIEW

**Comment by rjshrjndrn** [comment]
This installation method is valid from sunbird release-1.4. So we'll have to keep revisions of installation document.

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/262.

**Comment by nawabahmadreshi** [comment]
@rjshrjndrn, As discussed, Not sure about versioning as of now,  but we can add a new page under installation

Installing Sunbird 1.4 and Onwards (Tentative name)

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/262.

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/262.

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/262.

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/262.

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/262.

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/262.

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/262.

**Comment by lakhanmandloi** [comment]
Hello @rjshrjndrn,<br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/262.

**Comment by Sunitashelar** [comment]
Minor edits made. The page title is undergoing a change hence pull request not merged.

**Comment by Sunitashelar** [comment]
Merged the request. @mathewjpallan to look at the page during the hackathon.

**Pull request merged**
