### PR TITLE
Content Editor & Content Renderer API documentation

### PR DESCRIPTION
**Pull request by vinukumar-vs**
Added API documentation for content editor & content renderer

Please verify the jsdocument links, if it is not working need your help to udate the links.  
All the document related files are kept in ext-docs folder.

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hello @vinukumar-vs,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/343. <br/><br/> **Modified pages are -** <br /> <br/> **Modified sections are -** <br />

**Comment by lakhanmandloi** [comment]
Hello @vinukumar-vs,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/343. <br/><br/> **Modified pages are -** <br /> <br/> **Modified sections are -** <br />

**Comment by Sunitashelar** [comment]
Hi,
Can we discuss this before we merge this PR? Can see many external files that may not be required in this repo viz. Apache license file.

**Comment by lakhanmandloi** [comment]
Hello @vinukumar-vs,<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/343. <br/><br/> **Modified pages are -** <br /> <br/> **Modified sections are -** <br />

**Comment by vinukumar-vs** [comment]
@Sunitashelar @nawabahmadreshi 
I have committed the changes as we discussed.
Removed Unwanted files.

**Pull request merged**
